### PR TITLE
Issue58_IndexFilePerFolder

### PR DESCRIPTION
**Pull request by NewDark90**
This doesn't fully solve for the index file per folder, but it does allow for custom generation of index files by creating your own IIndexFileGenerator

### CODE REVIEW

**Comment by NewDark90** [comment]
@jburzynski I see this as more of a starting point that also opens things up just enough that I can do what I need. I'm not certain the direction you want to take past this.

**Comment by jburzynski** [comment]
It could stay like this for now, until some "full-fledged" functionality is implemented - I'll try to figure something out for the next release. This PR could also be helpful to other people who may want to generate index file(s) in some other way, as the current functionality is very limited. Thanks for the PR, I'll try to make the upload to NuGet tomorrow or on Wednesday.

BTW, are you using the CLI? To make it work with the CLI there would also need to be an option in `tgconfig.json`. Index file generator classes could be loaded in a similar way as generation specs.

**Comment by NewDark90** [comment]
I agree, it should support that. Let me get that in there.

**Comment by NewDark90** [comment]
@jburzynski I would like to solicit your advice on how you would handle setting up a default for GeneratorOptions.DefaultIndexFileGenerators given that it currently needs 3 objects build within the generator itself. I don't want to assume too much on how this should work, so I'd rather get your input.

**Comment by jburzynski** [comment]
I think that this would be ok for now, since it's only a temporary solution:

1. Add public properties in IIndexFileGenerator for the services (template service, generator options provider and file content handler provider), in order to do property injection later
2. Move IndexFileGenerator instance from GeneratorOptions to a set-only property in Generator (the set method injects the services to IIndexFileGenerator)
3. In the CLI, after an instance of IIndexFileGenerator is created, it's passed to the Generator instance using the set-only property (which in turn injects the needed services)

Of course, there are problems with this, because e.g. someone may want to use other services apart from these 3, but it's ok right now, because this will eventually be replaced with some less implementation-specific, more "regular" kind of functionality. I will try to do this for the next release.

Also, there is 1 more thing: I think IndexFileGeneratorCollection is not necessary. Converters have collections, because you can chain them, but I think with index file generators you would use only 1 generator instance (without a chain). Of course if you're chaining them deliberately and have some specific functionality in mind, it's ok.

**Comment by NewDark90** [comment]
Awesome, I'll see about doing this!

And you are correct about the index file generator collection. I think
being able to specify multiple would be good, but chaining them seems
useless to me. Thanks for the insight. 😄

**Comment by NewDark90** [comment]
Took a slightly different approach that I think is a bit better than described. Scream if you think there should be any other changes to it :)

**Comment by jburzynski** [comment]
That's right, it is a bit better :) I'll merge it and it will soon be released.

**Pull request merged**
