### PR TITLE
Fix AssemblyResolver skipping nuget folders on macos and linux

### PR DESCRIPTION
**Pull request by sdamian**

### CODE REVIEW

**Comment by jburzynski** [comment]
Thanks for your pull request! Can you pull request to dev instead of master?

**Comment by sdamian** [comment]
Done

**Comment by sdamian** [comment]
I have another one coming up with some more fixes ;)

**Comment by jburzynski** [comment]
Great, I look forward to it! :) I really appreciate you making changes to make it cross-platform - to be honest, I didn't really predict anyone would use TypeGen cross-platform, therefore (as you probably noticed) the whole code is Windows-only. I'll look at the changes when I have a free moment. Also, please let me know - e.g. in a pull request comment etc. - whenever you finish making all cross-platform-related changes, so that I can release a new version with all fixes. Thanks again for the effort and I look forward to all improvements :)

**Comment by sdamian** [comment]
This PR and #29 is all I have now regarding cross platform fixes. Plus a small cosmetic change in #30.
Looking forward to the next release 🤤

**Comment by jburzynski** [comment]
I just released 1.6.6 (should be listed in NuGet in a few moments). You can check if it works on linux/macos, in any case let me know :)

**Pull request merged**
