### PR TITLE
Issue58_IndexFilePerFolder_Revisions

### PR DESCRIPTION
**Pull request by NewDark90**
Doing some fixes and touch ups to the code base. Removed the generator collection. IIndexFileGeneratorParams, etc.

### CODE REVIEW

**Comment by jburzynski** [comment]
I'm thinking about waiting 2-3 days before releasing this change - this is just in case some other changes/bugs etc show up. Does that sound ok?

Also, can you please change the base to dev? Thanks!

**Comment by NewDark90** [comment]
Absolutely. No rush. And if you need or want to, feel free to refactor and
mangle that code to be whatever you think is appropriate for being a full
fledged feature. 👍
Greatly appreciate you working with me on this!

**Comment by NewDark90** [comment]
Hey, do you have any rough idea of when this will make it to master/release? No rush but I'd like to have an idea of what to expect.

**Comment by jburzynski** [comment]
I just released it in 2.3.4.

I wanted to finish the "complete" functionality before making a release, but it may take some more time, so it's released now instead.

I also would have one question about generating index files:
If there was a possibility to choose which directories you want to generate index files for (with the option to specify recursive/non-recursive), would that solve the problem in your case?

If this was sufficient, I'd aim to replace the existing functionality with something like described above - would this be enough?

**Comment by NewDark90** [comment]
Yeah that sounds a lot better honestly. It would solve my problem
fully. It also
means I wouldn't have to be so manual about creating the files myself which
does seem silly in retrospect.
The recursive option wouldn't help me specifically and I can't think of a
great use case for it.

Another consideration is to be able to specify the folders at runtime. As
in, let's say instead of doing any creation of index files, the current
'generator' would only serve to return a list of folders that the files
should be created at.
Might be unnecessary overkill, but throwing the idea out there in case it
resonates with you

**Comment by NewDark90** [comment]
In case the context matters at all, this is the generator I made so that I could get an index file on every first level folder. That's all I really wanted out of it, and it's definitely a lot of extra effort from the implementer to make something like it. I think it further cements that your suggestion is very good.

``` C# 
public class OneFolderDeepIndexFileGenerator : IIndexFileGenerator
{
        public IEnumerable<string> Generate(IIndexFileGeneratorParams parameters)
        {
            var generatedFilesFolderSplit = parameters.GeneratedFiles.Select(f => f.Split('/'));
            var groupedFilesByFirstLevel = generatedFilesFolderSplit.GroupBy(f =>
                f.FirstOrDefault(),
                f => String.Join("/", f.Skip(1)),
                (firstFolder, filePaths) => new
                {
                    Folder = firstFolder,
                    Files = filePaths
                });

            var indexFiles = new List<string>();
            foreach (var group in groupedFilesByFirstLevel)
            {
                var fileContent = CreateIndexFileContent(parameters, group.Folder, group.Files);

                string filename = "index." + parameters.GeneratorOptions.IndexFileExtension;
                filename = filename.EnsureRemovedPostfix(".");
                parameters.FileContentGenerated?.Invoke(this, new FileContentGeneratedArgs(null, Path.Combine(parameters.GeneratorOptions.BaseOutputDirectory, group.Folder, filename), fileContent));
            }

            return indexFiles;
        }

        private string CreateIndexFileContent(IIndexFileGeneratorParams parameters, string folder, IEnumerable<string> files)
        {
            string exports = files.Aggregate("", (prevExports, file) =>
            {
                string fileNameWithoutExt = file
                    .EnsureRemovedPostfix("." + parameters.GeneratorOptions.TypeScriptFileExtension)
                    .Replace("\\", "/");

                return prevExports + parameters.FillIndexExportTemplate(fileNameWithoutExt);
            });
            return parameters.FillIndexTemplate(exports);
        }
}
```

**Comment by jburzynski** [comment]
Yeah I thought you'd probably only need to select folders somehow. The current solution is good in a way that it actually makes it possible - before that you just weren't able to do this, so your PR is much appreciated :)

I haven't been using barrels very extensively, but I think you're right, you probably don't want to include any files recursively. Maybe if someone requests it it could be added later, but it may also never happen.

As for specifying folders at runtime, do you mean something like this (like an interactive command)?
```
> dotnet typegen generate
  (...)
  do you wish to generate an index file in some/ts/directory? [y/N]
  (...)
```

Thanks for posting the code! I'm thinking about allowing to specify index files in a generation spec like this:

```csharp
class SomeGenerationSpec : GenerationSpec
{
  public SomeGenerationSpec()
  {
    AddBarrel(string directory);
    AddBarrels(params int[] levels); // you can specify to only generate at level 1 or at levels 1 and 2, 1 and 3 etc.
  }
}
```

Do you think this would be ok? Like I mentioned, I don't have a lot of experience with index files, so input would be appreciated!

The reason I'm doing this in a generation spec is that you can combine them with the rest of your codebase - not sure it's very helpful in this case, but in general being able to create configuration from C# code may be helpful.

**Comment by jburzynski** [comment]
After reading a bit about barrel files / modules etc., I came to conclusion that creating the "standard"/"full" barrel structure should cover almost all cases, e.g.:

```
- app
  - components
    - home.component.ts
    - index.ts
  - utils.ts
  - index.ts
```

```typescript
// app/components/index.ts

export * from './home.component';
```

```typescript
// app/index.ts

export * from './utils';
export * from './components';
```

This way you can always access whichever directory you need. I'm not sure if there is ever a need to not create an index file for a directory. But then again I don't have that much experience on the subject, so once again any input is greatly appreciated :)

**Comment by NewDark90** [comment]
I quite like what you're suggesting. Both of those GenSpec functions give so much flexibility while being pretty simple to work with. I think you've got the right idea. 👍

**Comment by NewDark90** [comment]
And while I like the idea that the behavior described might be the default, having the extra bit of flexibility offered by those methods still sounds good. That's just my opinion though. :)

**Comment by jburzynski** [comment]
Thanks for the feedback! :) After all it's important that a tool like this is usable :) I'll try to come up with some "end" solution.

**Pull request merged**
